config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/gpt_test', to: "pages#gpt"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :campaigns do
    resources :active_players, only: %i[index new create]
    resources :encounters, only: %i[new create edit]
  end
  resources :encounters, only: %i[index show update]
  resources :players, only: %i[destroy]
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :active_players
  has_many :players, through: :active_players
  has_many :enemies

  # acts_as_list

  accepts_nested_attributes_for :enemies,reject_if: :reject_empty, allow_destroy: true
  # validates :skill_type, presence: true
  # validates :success, presence: true
  def reject_empty(attributes)
    attributes['name'].blank?
  end

  # def storeVariable(variable)
  #   @combatant = variable
  # end
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  def index
    @encounters = policy_scope(Encounter)
  end

  def show
    @encounter = Encounter.find(params[:id])
    @checking = @encounter
    @campaign = Campaign.find(@encounter.players.first.campaign_id)
    if @encounter.summary.present?
      @summary = OpenaiService.new("Create a DND combat narrative of a single combatant named #{@encounter.summary} attacking the single target named #{@encounter.target} in 60 words using these params [Damage Type: #{@encounter.skill_type},Hit:#{@encounter.success}, Killing Blow:#{@encounter.criticality}").call
    end
    authorize @encounter
  end

  def new
    @encounter = Encounter.new
    @encounter.enemies.build
    @campaign = Campaign.find(params[:campaign_id])
    authorize @encounter
  end

  def create
    @encounter = Encounter.new(encounter_params)
    @campaign = Campaign.find(params[:campaign_id])
    @encounter.players = @campaign.players
    authorize @encounter
    if @encounter.save
      redirect_to encounter_path(@encounter)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @encounter = Encounter.find(params[:id])
    @encounter.skill_type = nil
    @encounter.success = false
    @encounter.criticality = false

    # Combatant is an array containing player and enemies names
    # formatted for radio collection
    @combatant = []
    @encounter.players.map.each do |player|
      @combatant << player.character_name
    end
    @encounter.enemies.map.each do |enemy|
      @combatant << enemy.name
    end
    if params[:character].present?
      @encounter.summary = params[:character]
    else
      @encounter.summary = params[:enemy]
    end
    @encounter.save
    authorize @encounter
  end

  def update
    @encounter = Encounter.find(params[:id])
    authorize @encounter
    if @encounter.update(encounter_params)
      redirect_to encounter_path(@encounter)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def encounter_params
    params.require(:encounter).permit(:skill_type, :success, :criticality, :target, :summary, :position, enemies_attributes: [:name])
  end
end

app/views/encounters/_encounter_form.html.erb
<div class="nested-form-wrapper d-flex mt-2 justify-content-between align-items-center" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :name, class: "text-white" %>
  <%= f.text_field :name, class: "bg-success bg-opacity-10 text-white w-100 m-2" %>
  <button class="bg-transparent border border-0" type="button" data-action="nested-form#remove"><i class="fa-solid fa-user-minus text-muted m-2"></i></button>
  <%= f.hidden_field :_destroy %>
</div>

app/views/encounters/_narrative_modal.html.erb
<div class="modal" id='narrative-modal' tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/encounters/backup_show.html.erb
<body class="encounter-show-background d-flex flex-column align-items-center">
  <div class="container m-5 p-5 d-flex flex-column justify-content-center align-items-between">
    <h1 class="m-0 p-0">Roll for initiative! Whose turn is it?</h1>
    <div class="encounter-player-div bg-success p-3 mt-3 bg-opacity-25">
      <% i = 1 %>
      <% @encounter.players.each do |player| %>
        <div class="encounter-player-icon shadow-lg">
          <%= link_to edit_campaign_encounter_path(campaign_id: @campaign.id, character: player.character_name), class: 'text-decoration-none link-dark' do %>
            <%= image_tag "hero#{i}.jpg"%>
            <% i+=1 %>
            <span><%= player.character_name %></span>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="narrative-div">
      <div class="nav-world-card" style="padding: 15px">
        <% if @encounter.summary.present? %>
          <h3 class="text-center">Combat Summary</h3>
          <%= @summary %>
        <% else %>
          <h2 class="m-0 p-0">Select combatant to generate combat narrative</h2>
        <% end %>
      </div>
    </div>
    <div class="encounter-player-div bg-success p-3 mt-3 bg-opacity-25" style="margin-top: 40px">
      <% @encounter.enemies.each do |enemy| %>
        <div class="encounter-player-icon">
          <%= link_to edit_campaign_encounter_path(campaign_id: @campaign.id, enemy: enemy.name), class: 'text-decoration-none link-dark' do %>
            <%= image_tag "goblin.jpg"%>
            <span><%= enemy.name %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/encounters/edit.html.erb
<body class='world-background-image-div'>
  <div class="container mt-5 pt-5">
    <div class="text-center pt-2">
      <% if params[:enemy] %>
        <h1>COMBAT ROUND FOR <%= params[:enemy].upcase %>:</h1>
      <% else %>
        <h1>COMBAT ROUND FOR <%= params[:character].upcase %>:</h1>
      <% end %>
    </div>
    <h4 class='text-center text-muted pt-2 pb-3'>Step 3 of 3</h4>
    <h4 class='text-center text-white'>Select the combatant's damage type and target, then roll for hit and killing blow. Complete this step to generate narrative.</h4>
    <hr class="border border-top border-success border-2 w-100 mb-3">
    <%= simple_form_for [@campaign, @encounter], html: { class: 'encounter-form' } do |f| %>
      <%# <div class="nav-world-card" style="align-items: center"> %>
      <div style="position: relative">
        <span class="icon-text" id="icon-slot">SELECT YOUR DMG TYPE</span>
        <div class="icon">
          <ul class="menu">
            <%= f.collection_radio_buttons :skill_type, [['acid', 'Acid'], ['bludgeoning', 'Bludgeoning'], ['cold', 'Cold'], ['fire', 'Fire'], ['force', 'Force'],['lightning', 'Lightning'], ['necrotic', 'Necrotic'],['piercing', 'Piercing'], ['poison', 'Poison'],['psychic', 'Psychic'],['radiant', 'Radiant'],['slashing', 'Slashing'],['thunder', 'Thunder']],:first, :last, selected:' ',
            include_blank: true %>
          </ul>
        </div>
      </div>
      <div style="display:flex; flex-direction: column">
        <div class="nav-world-card" style="padding: 25px">
          <%= f.input :target,
                as: :radio_buttons,
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'target-wrapper',
                item_wrapper_class: 'target-item',
                input_html: {class: 'target-selector' },
                collection: @combatant %>
        </div>
        <div class="nav-world-card" style="padding: 25px;">
          <%= f.input :success, as: :boolean, :label => 'Toggle if target is hit', input_html: { class: "form-hidden toggle" }, id: 'encounter_success' %>
          <%= f.input :criticality, as: :boolean, :label => 'Toggle if target is killed', input_html: { class: "form-hidden toggle" }, id: 'encounter_criticality' %>
          <% f.hidden_field :summary, :value => "hello" %>
          <%= f.button :submit, 'Generate combat results', class: 'btn purple-button spinner-area', id: 'encounter-submit' %>
        </div>
      <% end %>
      <div class="hidden-spinner mt-5 me-4" style="margin-bottom: 35px">
        <div class="loader">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="title pt-4 ms-3">
          <p class ='text-white spinner-text'><%= "Sharpening swords"%></p>
        </div>
      </div>
    </div>
    <%# <form-hidden toggle> %>
    <%# </div> %>
    <%# </div> %>
  </div>
</body>
<%# damage type, target, success, criticality %>
<%= javascript_include_tag 'encounter' %>
<%= javascript_include_tag 'encounter-form' %>

app/views/encounters/index.html.erb
Yo what up from encounters / index

app/views/encounters/new.html.erb
<body class='world-background-image-div'>
  <div class="container d-flex flex-column mt-5 p-5">
    <h1 class="text-center">PREPARE FOR COMBAT</h1>
    <h4 class='text-center text-muted pt-2 pb-3'>Step 1 of 3</h4>
    <h4 class='text-center text-white pb-2'>Add adversaries for this specific encounter below.</h4>
    <hr class="border border-top border-success border-2 w-100 mb-5">
    <div class="card-container p-3 m-3 bg-dark bg-success bg-opacity-25" >
      <div class="card p-3 nav-world-card d-flex">
        <h2>Enter Enemy combatants:</h2>
        <%= simple_form_for [@campaign, @encounter], html: { data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }} do |f| %>
          <template data-nested-form-target="template">
            <%= f.fields_for :enemies, Enemy.new, child_index: 'NEW_RECORD' do |enemy_fields| %>
              <%= render "encounter_form", f: enemy_fields %>
            <% end %>
          </template>
          <div data-nested-form-target="target">
            <button class="bg-transparent border border-0" type="button" data-action="nested-form#add"><i class="fa-solid fa-user-plus text-success m-2"></i></button>
          </div>
          <div class="encounter-new-buttons-div d-flex flex-wrap">
            <%= f.button :submit, "Begin Combat!", class: "btn btn-success m-2"%>
            <%= link_to 'Exit Campaign', campaigns_path, class: "btn btn-success m-2"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/encounters/show.html.erb
<% content_for :meta_title, "#{@encounter.players.last.campaign.world_name
} is on #{DEFAULT_META["meta_product_name"]}" %>
<%#=Meta Information Above"%>
<body class='bg-black text-white'>
  <div class="container d-flex flex-column mt-5 pt-5">
    <div>
      <% if @encounter.summary.present? %>
        <h1 class="text-center">
          SELECT NEXT COMBATANT
        </h1>
      <% else %>
        <h1 class="text-center">
          SELECT COMBATANT
        </h1>
      <% end %>
      <h4 class='text-center text-muted pt-2 pb-3'>Step 2 of 3</h4>
      <% if @encounter.summary.present? %>
        <div class="accordion">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <% if @encounter.summary.present? %>
                <button class="accordion-button" style="border-radius: 24px"type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Display Narrative
                </button>
              <% end %>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <%# put stuff in the accordion here %>
                <div class="text-white">
                  <% if @encounter.summary.present? %>
                    <h3 class="text-center mb-3">Narrative</h3>
                    <h5 class ='text-white p-2'><%= @summary %></h5>
                  <% else %>
                    <p class="text-center mb-0">The combat narrative for this round will be displayed here after step 3.</p>
                  <% end %>
                </div>
                <%# end accordion stuff here %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <h4 class='text-center text-white pb-2'>Roll for initiative. You can shuffle the combatant cards and put them in order from highest to lowest roll. Then, choose the current combatant to proceed.</h4>
      <% end %>
      <hr>
      <%# put accordion here %>
      <%# end accordion here %>
      <ul data-controller="sortable" data-sortable-animation-value="150" class="container d-flex align-items-center justify-content-center flex-wrap gap-2 mt-2">
        <% i = 1 %>
        <% @encounter.players.each do |player| %>
          <li class="combantant-card">
            <div class="card-product">
              <%= link_to edit_campaign_encounter_path(campaign_id: @campaign.id, character: player.character_name), class: 'text-decoration-none text-white' do %>
                <span><%= image_tag "player#{i}.jpg", class: "img", style: "border-radius: 16px 0  0 16px;" %></span>
                <div class="card-product-infos">
                  <span><%= player.character_name %></span>
                <% end %>
              </div>
            </div>
          </li>
          <% i += 1 %>
        <% end %>
        <% @encounter.enemies.each do |enemy| %>
          <li class="combantant-card">
            <div class="card-product">
              <%= link_to edit_campaign_encounter_path(campaign_id: @campaign.id, enemy: enemy.name), class: 'text-decoration-none text-white' do %>
                <span><%= image_tag "goblin.jpg", class: "img bg-black bg-opacity-75", style: "border-radius: 16px 0  0 16px; height: 118px;" %></span>
                <div class="card-product-infos">
                  <span><%= enemy.name %></span>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="text-center mt-2 mb-3">
      <%= link_to 'Exit Combat', new_campaign_encounter_path(@campaign), class: "btn purple-button m-2"%>
    </div>
  </div>
</div>
</body>