config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/gpt_test', to: "pages#gpt"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :campaigns do
    resources :active_players, only: %i[index new create]
    resources :encounters, only: %i[new create edit]
  end
  resources :encounters, only: %i[index show update]
  resources :players, only: %i[destroy]
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user

  has_many :players, dependent: :destroy
  has_one :ai_text, dependent: :destroy

  validates :world_name, presence: true
  validates :world_biome, presence: true
  validates :world_mood, presence: true
  validates :world_weather, presence: true
  validates :players, presence: true

  accepts_nested_attributes_for :players, allow_destroy: true

  BIOMES = %i[forest desert jungle plains cavern tundra city]
  WEATHERS = %i[clear cloudy rainy snowy windy stormy]
  MOODS = %i[comedic romantic dark epic medieval high]
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = policy_scope(Campaign)
  end

  def show
    @campaign = Campaign.all.find(params[:id])
    @user = current_user
    authorize @campaign
    @service = OpenaiService.new("Create a description with a tone of #{@campaign.world_mood} DND world in 75 words using these params [World Name:#{@campaign.world_name}, Biome:#{@campaign.world_biome}, Weather:#{@campaign.world_weather}").call
    # if @campaign.ai_texts_ids.present?
    #   @service = @campaign.ai_texts
    # else
    #   @campaign.ai_texts OpenaiService.new("Create a description with a tone of #{@campaign.world_mood} DND world in 75 words using these params [World Name:#{@campaign.world_name}, Biome:#{@campaign.world_biome}, Weather:#{@campaign.world_weather}").call
    #   @service = @campaign.ai_texts_ids
    # end
  end

  def edit
    @campaign = Campaign.find(params[:id])
    @players = @campaign.players
    authorize @campaign
  end

  def update
    @campaign = Campaign.find(params[:id])
    authorize @campaign
    if @campaign.update(campaign_params)
      redirect_to campaign_path(@campaign)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @campaign = Campaign.new
    @user = current_user
    @campaign.players.build
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @user = current_user
    @campaign.user = @user
    authorize @campaign
    if @campaign.save
      redirect_to campaign_path(@campaign)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @campaign = Campaign.find(params[:id])
  #   @campaign.players.destroy
  #   @campaign.ai_texts.destroy
  #   @campaign.destroy
  # end

  private

  def campaign_params
    params.require(:campaign).permit(:world_name, :world_biome, :world_mood, :world_weather, players_attributes: %i[player_name character_name])
  end
end

app/views/campaigns/_player_form.html.erb
<div class="nested-form-wrapper m-1" data-new-record="<%= f.object.new_record? %>">
  <div class="container border border-success border-1 rounded p-3 mb-3">
    <div class="row">
      <div class="col">
        <%= f.label :player_name, class: "mb-3" %>
      </div>
      <div class="col">
        <%= f.text_field :player_name, class: "bg-black border border-success border-rounded text-white  w-100" %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.label :character_name, class: "mb-3" %>
      </div>
      <div class="col">
        <%= f.text_field :character_name, class: "bg-black border border-success border-rounded text-white w-100"%>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <button class="bg-transparent border border-0" type="button" data-action="nested-form#remove"><i class="fa-solid fa-user-minus text-muted m-2"></i></button>
        <%= f.hidden_field :_destroy %>
      </div>
      <div class="col"></div>
    </div>
  </div>
</div>

app/views/campaigns/backup.html.erb
<div class="world-card-container">
  <div class="world-card">
    <!-- Upper div with circular icon and text -->
    <div class="world-card-header">
      <%# <img alt="portrait" class="world-card-icon" src="/assets/blue.jpg"> %>
      <%= image_tag "blue.jpg", class:"world-card-icon"%>
    </div>
    <!-- Middle div with image -->
    <div class="world-card-image img">
      <%= image_tag "#{div_1_info}.jpg"%>
    </div>
    <!-- Lower div with four elements containing small text -->
    <div class="world-card-footer">
      <p class="world-footer-text">World Name: Dances With Goblins</p>
      <p class="world-footer-text">Biome: <%= div_1_info.capitalize %></p>
      <p class="world-footer-text">Weather: <%= %w[clear cloudy rainy snowy windy stormy].sample.capitalize %></p>
      <p class="world-footer-text">Mood: <%= %w[comedic romantic dark epic medieval high].sample.capitalize %></p>
    </div>
  </div>
  <div class="world-card">
    <!-- Upper div with circular icon and text -->
    <div class="world-card-header">
      <%= image_tag "purple-gem.jpg", class:"world-card-icon"%>
    </div>
    <!-- Middle div with image -->
    <div class="world-card-image img">
      <%= image_tag "#{div_2_info}.jpg"%>
    </div>
    <!-- Lower div with four elements containing small text -->
    <div class="world-card-footer">
      <p class="world-footer-text">Campaign Name: Easter Day</p>
      <p class="world-footer-text">Biome: <%= div_2_info.capitalize %></p>
      <p class="world-footer-text">Weather: <%= %w[clear cloudy rainy snowy windy stormy].sample.capitalize%></p>
      <p class="world-footer-text">Mood: <%= %w[comedic romantic dark epic medieval high].sample.capitalize %></p>
    </div>
  </div>
  <div class="world-card">
    <!-- Upper div with circular icon and text -->
    <div class="world-card-header">
      <%= image_tag "gold-gem.jpg", class:"world-card-icon"%>
    </div>
    <!-- Middle div with image -->
    <div class="world-card-image img">
      <%= image_tag "#{div_3_info}.jpg"%>
    </div>
    <!-- Lower div with four elements containing small text -->
    <div class="world-card-footer">
      <p class="world-footer-text">Campaign Name: Rat Man Returns</p>
      <p class="world-footer-text">Biome: <%= div_3_info.capitalize %></p>
      <p class="world-footer-text">Weather: <%= %w[clear cloudy rainy snowy windy stormy].sample.capitalize%></p>
      <p class="world-footer-text">Mood: <%= %w[comedic romantic dark epic medieval high].sample.capitalize %></p>
    </div>
  </div>
</div>

app/views/campaigns/edit.html.erb
<body class="bg-black">
  <div class="container d-flex flex-column mt-5 py-5 justify-content-center align-items-center">
    <div>
      <h1 class="text-center">CAMPAIGN CREATION</h1>
      <h3 class="text-center p-3">Name your campaign, then decide your session biome, weather, and mood. These can be changed later.
      </h3>
    </div>
    <div class="category-wrapper border border-success border-3 rounded-0 bg-black d-flex flex-wrap mx-2 p-4 text-white">
      <%= simple_form_for [@campaign], html: { data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }} do |f| %>
        <%= f.input :world_name, label:"Campaign name", id: "form-field"%>
        <%= f.input :world_biome, label:"Biome",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::BIOMES %>
        <%= f.input :world_weather, label:"Weather",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::WEATHERS %>
        <%= f.input :world_mood, label:"Mood",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::MOODS %>
        <template data-nested-form-target="template">
          <%= f.fields_for :players, Player.new, child_index: 'NEW_RECORD' do |player_fields| %>
            <%= render "player_form", f: player_fields %>
          <% end %>
        </template>
        <div data-nested-form-target="target"></div>
        <button class="btn btn-success m-2" type="button" data-action="nested-form#add">Add character</button>
      </div>
      <div class="d-grid gap-2 col-3 pt-3 pb-3 mx-auto spinner-area">
        <%= f.button :submit, "Create Campaign", class: "btn purple-button", style: "width: auto"%>
      </div>
    <% end %>
    <div class="hidden-spinner mt-5 me-4 mb-2">
      <div class="loader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div class="title pt-4 ms-3 text-white">
        <p id='spinner-text'>Generating biome</p>
      </div>
    </div>
  </div>
</div>
</body>
<%= javascript_include_tag 'campaign' %>

app/views/campaigns/index.html.erb
<body class="bg-black text-white">
  <div class="container mt-5 pt-5 d-flex flex-column align-items-center">
    <h1 class="text-center">CAMPAIGNS</h1>
    <h3 class="text-center p-3">Radiant uses details from your game session to craft a personalized introduction to your campaign. To get started, create a new campaign, or click "Existing Campaigns" to select from previous ones.</h3>
    <hr class="border border-top border-success border-2 w-100 mb-5">
    <%= link_to new_campaign_path(@campaign), class: 'text-decoration-none link-dark' do %>
      <div class="btn btn-success py-3 px-5 m-5" style="border-radius: 24px">
        New Campaign
      </div>
    <% end %>
    <div class="accordion" style="margin-bottom: 50px">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button collapsed" style="border-radius: 24px"type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Existing Campaigns
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div class="container d-flex align-items-center justify-content-center flex-wrap p-3">
              <% @campaigns.each do |campaign| %>
                <div class="campaign-card relative">
                  <div class="card-world-name">
                    <%=campaign.world_name.capitalize %>
                  </div>
                  <%= link_to campaign_path(campaign), class: "text-decoration-none" do %>
                    <div>
                      <%=image_tag("#{campaign.world_biome}.jpg")%>
                    </div>
                  <% end %>
                  <%=link_to campaign_path(campaign), class: "absolute", data: {turbo_method: :delete, turbo_confirm: "Do you want to delete this campaign?"} do %>
                    <i class="fa-solid fa-trash-can text-muted m-2"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  <%#= link_to 'Back to the homepage', root_path, class: 'btn world-button w-50'   %>

app/views/campaigns/new.html.erb
<% div_1_info = %w[forest desert jungle plains cavern tundra city].sample %>
<% div_2_info = (%w[forest desert jungle plains cavern tundra city] -[div_1_info]).sample %>
<% div_3_info = (%w[forest desert jungle plains cavern tundra city] - [div_1_info,div_2_info]).sample %>
<body class="bg-black">
  <div class="container d-flex flex-column mt-5 py-5 justify-content-center align-items-center">
    <div>
      <h1 class="text-center">CAMPAIGN CREATION</h1>
      <h3 class="text-center p-3">Name your campaign, then decide your session biome, weather, and mood. These can be changed later.
      </h3>
    </div>
    <div class="category-wrapper border border-success border-3 rounded-0 bg-black d-flex flex-wrap mx-2 p-4 text-white">
      <%= simple_form_for [@campaign], html: { data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }} do |f| %>
        <%= f.input :world_name, label:"Campaign name", id: "form-field"%>
        <%= f.input :world_biome, label:"Biome",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::BIOMES %>
        <%= f.input :world_weather, label:"Weather",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::WEATHERS %>
        <%= f.input :world_mood, label:"Mood",
          as: :radio_buttons,
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'},
          collection: Campaign::MOODS %>
        <template data-nested-form-target="template">
          <%= f.fields_for :players, Player.new, child_index: 'NEW_RECORD' do |player_fields| %>
            <%= render "player_form", f: player_fields %>
          <% end %>
        </template>
        <div data-nested-form-target="target"></div>
        <button class="btn btn-success m-2" type="button" data-action="nested-form#add">Add character</button>
      </div>
      <div class="d-grid gap-2 col-3 pt-3 pb-3 mx-auto spinner-area">
        <%= f.button :submit, "Create Campaign", class: "btn purple-button", style: "width: auto"%>
      </div>
    <% end %>
    <div class="hidden-spinner mt-5 me-4 mb-2">
      <div class="loader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div class="title pt-4 ms-3 text-white">
        <p id='spinner-text'>Generating biome</p>
      </div>
    </div>
  </div>
</div>
</body>
<%= javascript_include_tag 'campaign' %>

app/views/campaigns/show.html.erb
<body class="nav-world-background">
  <div class="nav-world-container">
    <div class="smaller-card">
      <div class="nav-world-card-header">
        <h3 class="header-text"><%= @campaign.world_name.capitalize %></h3>
      </div>
      <div class="nav-world-card-image">
        <%= image_tag "#{@campaign.world_biome}.jpg"%>
      </div>
      <div class="nav-world-card-footer">
        <ul class="nav-world-footer-left no-bullets">
          <li><span style="font-weight:bold">Biome:</span> <%= @campaign.world_biome.capitalize  %></li>
          <li><span style="font-weight:bold">Mood:</span> <%= @campaign.world_mood.capitalize  %></li>
          <li><span style="font-weight:bold">Weather:</span> <%= @campaign.world_weather.capitalize  %></li>
        </ul>
        <div class="nav-world-footer-right">
          <p style="font-weight:bold; margin-bottom:2px; text-decoration: underline;">  Characters  </p>
          <div class="nav-world-player-list">
            <% @campaign.players.each do |player| %>
              <div>
                <%= player.character_name %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="nav-world-right-div">
      <div class="nav-world-text-card">
        <h3 class="header-text" style="margin-bottom: 10px;">World Description</h3>
        <p class="header-text"><%= @service %></p>
      </div>
      <%= link_to new_campaign_encounter_path(@campaign), class: 'text-decoration-none link-dark' do %>
        <div class="btn purple-button" style="margin-top: 15%; margin-bottom: 35px">
          Enter Campaign
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>